version: "3.7"
services:
  bento:
    image: ${REGISTRY}/${APP}:${APP_VERSION}dev
    environment:
      DEV: "True"
    volumes:
      # To develop with hot-reload, this mounts your Bento project into a container
      - ${BUILDER_REPO}/${APP}/:/app/${APP}/
      # You may find it useful to mount and edit the Bento codebase
      - ${HOME}/${BENTO_REPO}/bento/:${PYTHON_SP}/bento/
    # Override the gunicorn default command
    command: ["python3", "-m", "entrypoint"]
